export const majors = [
  { label: 'General Agriculture', value: 1 },
  { label: 'Agriculture Production And Management', value: 2 },
  { label: 'Agricultural Economics', value: 3 },
  { label: 'Animal Sciences', value: 4 },
  { label: 'Food Science', value: 5 },
  { label: 'Plant Science And Agronomy', value: 6 },
  { label: 'Soil Science', value: 7 },
  { label: 'Miscellaneous Agriculture', value: 8 },
  { label: 'Forestry', value: 9 },
  { label: 'Natural Resources Management', value: 10 },
  { label: 'Fine Arts', value: 11 },
  { label: 'Drama And Theater Arts', value: 12 },
  { label: 'Music', value: 13 },
  { label: 'Visual And Performing Arts', value: 14 },
  { label: 'Commercial Art And Graphic Design', value: 15 },
  { label: 'Film Video And Photographic Arts', value: 16 },
  { label: 'Studio Arts', value: 17 },
  { label: 'Miscellaneous Fine Arts', value: 18 },
  { label: 'Environmental Science', value: 19 },
  { label: 'Biology', value: 20 },
  { label: 'Biochemical Sciences', value: 21 },
  { label: 'Botany', value: 22 },
  { label: 'Molecular Biology', value: 23 },
  { label: 'Ecology', value: 24 },
  { label: 'Genetics', value: 25 },
  { label: 'Microbiology', value: 26 },
  { label: 'Pharmacology', value: 27 },
  { label: 'Physiology', value: 28 },
  { label: 'Zoology', value: 29 },
  { label: 'Neuroscience', value: 30 },
  { label: 'Miscellaneous Biology', value: 31 },
  { label: 'Cognitive Science And Biopsychology', value: 32 },
  { label: 'General Business', value: 33 },
  { label: 'Accounting', value: 34 },
  { label: 'Actuarial Science', value: 35 },
  { label: 'Business Management And Administration', value: 36 },
  { label: 'Operations Logistics And E-Commerce', value: 37 },
  { label: 'Business Economics', value: 38 },
  { label: 'Marketing And Marketing Research', value: 39 },
  { label: 'Finance', value: 40 },
  { label: 'Human Resources And Personnel Management', value: 41 },
  { label: 'International Business', value: 42 },
  { label: 'Hospitality Management', value: 43 },
  { label: 'Management Information Systems And Statistics', value: 44 },
  { label: 'Miscellaneous Business & Medical Administration', value: 45 },
  { label: 'Communications', value: 46 },
  { label: 'Journalism', value: 47 },
  { label: 'Mass Media', value: 48 },
  { label: 'Advertising And Public Relations', value: 49 },
  { label: 'Communication Technologies', value: 50 },
  { label: 'Computer And Information Systems', value: 51 },
  { label: 'Computer Programming And Data Processing', value: 52 },
  { label: 'Computer Science', value: 53 },
  { label: 'Information Sciences', value: 54 },
  { label: 'Computer Administration Management And Security', value: 55 },
  { label: 'Computer Networking And Telecommunications', value: 56 },
  { label: 'Mathematics', value: 57 },
  { label: 'Applied Mathematics', value: 58 },
  { label: 'Statistics And Decision Science', value: 59 },
  { label: 'Mathematics And Computer Science', value: 60 },
  { label: 'General Education', value: 61 },
  { label: 'Educational Administration And Supervision', value: 62 },
  { label: 'School Student Counseling', value: 63 },
  { label: 'Elementary Education', value: 64 },
  { label: 'Mathematics Teacher Education', value: 65 },
  { label: 'Physical And Health Education Teaching', value: 66 },
  { label: 'Early Childhood Education', value: 67 },
  { label: 'Science And Computer Teacher Education', value: 68 },
  { label: 'Secondary Teacher Education', value: 69 },
  { label: 'Special Needs Education', value: 70 },
  { label: 'Social Science Or History Teacher Education', value: 71 },
  { label: 'Teacher Education: Multiple Levels', value: 72 },
  { label: 'Language And Drama Education', value: 73 },
  { label: 'Art And Music Education', value: 74 },
  { label: 'Miscellaneous Education', value: 75 },
  { label: 'Library Science', value: 76 },
  { label: 'Architecture', value: 77 },
  { label: 'General Engineering', value: 78 },
  { label: 'Aerospace Engineering', value: 79 },
  { label: 'Biological Engineering', value: 80 },
  { label: 'Architectural Engineering', value: 81 },
  { label: 'Biomedical Engineering', value: 82 },
  { label: 'Chemical Engineering', value: 83 },
  { label: 'Civil Engineering', value: 84 },
  { label: 'Computer Engineering', value: 85 },
  { label: 'Electrical Engineering', value: 86 },
  { label: 'Engineering Mechanics Physics And Science', value: 87 },
  { label: 'Environmental Engineering', value: 88 },
  { label: 'Geological And Geophysical Engineering', value: 89 },
  { label: 'Industrial And Manufacturing Engineering', value: 90 },
  { label: 'Materials Engineering And Materials Science', value: 91 },
  { label: 'Mechanical Engineering', value: 92 },
  { label: 'Metallurgical Engineering', value: 93 },
  { label: 'Mining And Mineral Engineering', value: 94 },
  { label: 'Naval Architecture And Marine Engineering', value: 95 },
  { label: 'Nuclear Engineering', value: 96 },
  { label: 'Petroleum Engineering', value: 97 },
  { label: 'Miscellaneous Engineering', value: 98 },
  { label: 'Engineering Technologies', value: 99 },
  { label: 'Engineering And Industrial Management', value: 100 },
  { label: 'Electrical Engineering Technology', value: 101 },
  { label: 'Industrial Production Technologies', value: 102 },
  { label: 'Mechanical Engineering Related Technologies', value: 103 },
  { label: 'Miscellaneous Engineering Technologies', value: 104 },
  { label: 'Materials Science', value: 105 },
  { label: 'Nutrition Sciences', value: 106 },
  { label: 'General Medical And Health Services', value: 107 },
  { label: 'Communication Disorders Sciences And Services', value: 108 },
  { label: 'Health And Medical Administrative Services', value: 109 },
  { label: 'Medical Assisting Services', value: 110 },
  { label: 'Medical Technologies Technicians', value: 111 },
  { label: 'Health And Medical Preparatory Programs', value: 112 },
  { label: 'Nursing', value: 113 },
  { label: 'Pharmacy Pharmaceutical Sciences And Administration', value: 114 },
  { label: 'Treatment Therapy Professions', value: 115 },
  { label: 'Community And Public Health', value: 116 },
  { label: 'Miscellaneous Health Medical Professions', value: 117 },
  { label: 'Area Ethnic And Civilization Studies', value: 118 },
  { label: 'Linguistics And Comparative Language And Literature', value: 119 },
  { label: 'French German Latin And Other Common Foreign Language Studies', value: 120 },
  { label: 'Other Foreign Languages', value: 121 },
  { label: 'English Language And Literature', value: 122 },
  { label: 'Composition And Rhetoric', value: 123 },
  { label: 'Liberal Arts', value: 124 },
  { label: 'Humanities', value: 125 },
  { label: 'Intercultural And International Studies', value: 126 },
  { label: 'Philosophy And Religious Studies', value: 127 },
  { label: 'Theology And Religious Vocations', value: 128 },
  { label: 'Anthropology And Archeology', value: 129 },
  { label: 'Art History And Criticism', value: 130 },
  { label: 'History', value: 131 },
  { label: 'United States History', value: 132 },
  { label: 'Cosmetology Services And Culinary Arts', value: 133 },
  { label: 'Family And Consumer Sciences', value: 134 },
  { label: 'Military Technologies', value: 135 },
  { label: 'Physical Fitness Parks Recreation And Leisure', value: 136 },
  { label: 'Construction Services', value: 137 },
  { label: 'Electrical, Mechanical, And Precision Technologies And Production', value: 138 },
  { label: 'Transportation Sciences And Technologies', value: 139 },
  { label: 'Multi/Interdisciplinary Studies', value: 140 },
  { label: 'Court Reporting', value: 141 },
  { label: 'Pre-Law And Legal Studies', value: 142 },
  { label: 'Criminal Justice And Fire Protection', value: 143 },
  { label: 'Public Administration', value: 144 },
  { label: 'Public Policy', value: 145 },
  { label: "N/A (Less Than Bachelor'S Degree)", value: 146 },
  { label: 'Physical Sciences', value: 147 },
  { label: 'Astronomy And Astrophysics', value: 148 },
  { label: 'Atmospheric Sciences And Meteorology', value: 149 },
  { label: 'Chemistry', value: 150 },
  { label: 'Geology And Earth Science', value: 151 },
  { label: 'Geosciences', value: 152 },
  { label: 'Oceanography', value: 153 },
  { label: 'Physics', value: 154 },
  { label: 'Multi-Disciplinary Or General Science', value: 155 },
  { label: 'Nuclear, Industrial Radiology, And Biological Technologies', value: 156 },
  { label: 'Psychology', value: 157 },
  { label: 'Educational Psychology', value: 158 },
  { label: 'Clinical Psychology', value: 159 },
  { label: 'Counseling Psychology', value: 160 },
  { label: 'Industrial And Organizational Psychology', value: 161 },
  { label: 'Social Psychology', value: 162 },
  { label: 'Miscellaneous Psychology', value: 163 },
  { label: 'Human Services And Community Organization', value: 164 },
  { label: 'Social Work', value: 165 },
  { label: 'Interdisciplinary Social Sciences', value: 166 },
  { label: 'General Social Sciences', value: 167 },
  { label: 'Economics', value: 168 },
  { label: 'Criminology', value: 169 },
  { label: 'Geography', value: 170 },
  { label: 'International Relations', value: 171 },
  { label: 'Political Science And Government', value: 172 },
  { label: 'Sociology', value: 173 },
  { label: 'Miscellaneous Social Sciences', value: 174 },
  { label: 'Other', value: 175 },
]
