services:
  api:
    container_name: ${DOCKER_PROJECT_NAME}-api
    restart: on-failure
    build:
      context: ../
      dockerfile: ./Docker/app.e2e.Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - ../.env
    environment:
      - DATABASE_HOST=${DOCKER_PROJECT_NAME}-postgres
      - MAIL_HOST=${DOCKER_PROJECT_NAME}-maildev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: ${DOCKER_PROJECT_NAME}-db
    image: postgres:16.0-alpine
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  
  maildev:
    container_name: ${DOCKER_PROJECT_NAME}-maildev
    build:
      context: ../
      dockerfile: ./Docker/maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379
