services:
  app:
    container_name: teameights-api
    restart: on-failure
    build:
      context: ../
      dockerfile: ./Docker/e2e.Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app

  postgres:
    container_name: teameights-db
    image: postgres:16.0-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    
  maildev:
    build:
      context: ../
      dockerfile: ./Docker/maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATABASE_PATH_LOCAL}/data
