export const allowedUpdateUserFields: string[] = [
	'email',
	'username',
	'fullName',
	'dateOfBirth',
	'description',
	'concentration',
	'country',
	'experience',
	'isLeader',
	'links',
	'programmingLanguages',
	'frameworks',
	'universityData',
	'jobData',
	'projectData',
];
