import {
  AfterEffects,
  Animate,
  Aseprite,
  Assembly,
  Bash,
  Blender,
  C,
  CinemaFourD,
  CPlusPlus,
  CSharp,
  CSS,
  Dart,
  Figma,
  Firefly,
  Framer,
  Go,
  Houdini,
  HTML,
  Illustrator,
  Indesign,
  Invision,
  Java,
  JS,
  Julia,
  Kotlin,
  Lottie,
  Lua,
  Matlab,
  Maya,
  Midjourney,
  Modo,
  Perl,
  Photoshop,
  Php,
  Premier,
  Procreate,
  Protopie,
  Python,
  R,
  Readymag,
  Ruby,
  Rust,
  Scala,
  Shopify,
  Spline,
  SQL,
  Substance3d,
  Swift,
  ThreeDsMax,
  TS,
  Vectary,
  Webflow,
  Weblium,
  Xd,
  Zbrush,
  Sketch,
  Asana,
  Clickup,
  Jira,
  MicrosoftProject,
  Miro,
  Notion,
  Slack,
  Trello,
} from '@/shared/assets';

interface LanguageOptions {
  [lang: string]: JSX.Element;
}

export const badgeIcons: LanguageOptions = {
  // Programming languages
  Assembly: <Assembly />,
  Bash: <Bash />,
  C: <C />,
  'C#': <CSharp />,
  'C++': <CPlusPlus />,
  CSS: <CSS />,
  Dart: <Dart />,
  Go: <Go />,
  HTML: <HTML />,
  Java: <Java />,
  JavaScript: <JS />,
  Julia: <Julia />,
  Kotlin: <Kotlin />,
  Lua: <Lua />,
  MATLAB: <Matlab />,
  Perl: <Perl />,
  PHP: <Php />,
  Python: <Python />,
  R: <R />,
  Ruby: <Ruby />,
  Rust: <Rust />,
  Scala: <Scala />,
  SQL: <SQL />,
  Swift: <Swift />,
  TypeScript: <TS />,

  // Designer tools
  '3ds Max': <ThreeDsMax />,
  'After Effects': <AfterEffects />,
  Aseprite: <Aseprite />,
  Animate: <Animate />,
  'Blender 3D': <Blender />,
  'Cinema 4D': <CinemaFourD />,
  Figma: <Figma />,
  Firefly: <Firefly />,
  Framer: <Framer />,
  Houdini: <Houdini />,
  Illustrator: <Illustrator />,
  InDesign: <Indesign />,
  InVision: <Invision />,
  Lottie: <Lottie />,
  Maya: <Maya />,
  Midjourney: <Midjourney />,
  Modo: <Modo />,
  Photoshop: <Photoshop />,
  'Premier Pro': <Premier />,
  Procreate: <Procreate />,
  'Proto Pie': <Protopie />,
  Readymag: <Readymag />,
  Shopify: <Shopify />, // New item
  Sketch: <Sketch />,
  Spline: <Spline />,
  'Substance 3D Designer': <Substance3d />,
  Vectary: <Vectary />,
  Webflow: <Webflow />, // New item
  Weblium: <Weblium />, // New item
  XD: <Xd />,
  ZBrush: <Zbrush />,

  // Project manager tools
  Asana: <Asana />,
  ClickUp: <Clickup />,
  JIRA: <Jira />,
  'Microsoft Project': <MicrosoftProject />,
  Miro: <Miro />,
  Notion: <Notion />,
  Slack: <Slack />,
  Trello: <Trello />,
};
