export const designerTools = [
  { label: '3ds Max', value: '3ds_max' },
  { label: 'After Effects', value: 'after_effects' },
  { label: 'Aseprite', value: 'aseprite' },
  { label: 'Animate', value: 'animate' },
  { label: 'Blender 3D', value: 'blender_3d' },
  { label: 'Cinema 4D', value: 'cinema_4d' },
  { label: 'Figma', value: 'figma' },
  { label: 'Firefly', value: 'firefly' },
  { label: 'Framer', value: 'framer' },
  { label: 'Houdini', value: 'houdini' },
  { label: 'Illustrator', value: 'illustrator' },
  { label: 'InDesign', value: 'indesign' },
  { label: 'InVision', value: 'invision' },
  { label: 'Lottie', value: 'lottie' },
  { label: 'Maya', value: 'maya' },
  { label: 'Midjourney', value: 'midjourney' },
  { label: 'Modo', value: 'modo' },
  { label: 'Photoshop', value: 'photoshop' },
  { label: 'Premier Pro', value: 'premier_pro' },
  { label: 'Procreate', value: 'procreate' },
  { label: 'Proto Pie', value: 'proto_pie' },
  { label: 'Readymag', value: 'readymag' },
  { label: 'Shopify', value: 'shopify' }, // New item
  { label: 'Sketch', value: 'sketch' },
  { label: 'Spline', value: 'spline' },
  { label: 'Substance 3D Designer', value: 'substance_3d_designer' },
  { label: 'Vectary', value: 'vectary' },
  { label: 'Webflow', value: 'webflow' }, // New item
  { label: 'Weblium', value: 'weblium' }, // New item
  { label: 'XD', value: 'xd' },
  { label: 'ZBrush', value: 'zbrush' },
];
