export const frameworks = [
  { label: 'Node.js', value: 'nodejs' },
  { label: 'Ruby', value: 'ruby' },
  { label: 'Angular', value: 'angular' },
  { label: 'Hadoop', value: 'hadoop' },
  { label: 'Ember', value: 'ember' },
  { label: 'Django', value: 'django' },
  { label: 'Docker', value: 'docker' },
  { label: 'Redux', value: 'redux' },
  { label: 'Spring', value: 'spring' },
  { label: 'Spark', value: 'spark' },
  { label: 'Backbone', value: 'backbone' },
  { label: 'jQuery', value: 'jquery' },
  { label: 'MUI', value: 'mui' },
  { label: 'ASP.NET', value: 'aspnet' },
  { label: 'NumPy', value: 'numpy' },
  { label: 'Flutter', value: 'flutter' },
  { label: 'React N.', value: 'reactnative' },
  { label: 'Flask', value: 'flask' },
  { label: 'Bootstrap', value: 'bootstrap' },
  { label: 'GraphQL', value: 'graphql' },
  { label: 'Laravel', value: 'laravel' },
  { label: 'PyTorch', value: 'pytorch' },
  { label: 'Express', value: 'express' },
  { label: 'Android', value: 'android' },
  { label: 'AWS', value: 'aws' },
  { label: 'Cypress', value: 'cypress' },
  { label: 'Electron', value: 'electron' },
  { label: 'Embedded C', value: 'embeddedc' },
  { label: 'Ionic', value: 'ionic' },
  { label: 'IOS', value: 'ios' },
  { label: 'Keras', value: 'keras' },
  { label: 'Kotlin M.', value: 'kotlinmobile' },
  { label: 'Kubernetes', value: 'kubernetes' },
  { label: 'MXNet', value: 'mxnet' },
  { label: 'Next.js', value: 'nextjs' },
  { label: 'Playwright', value: 'playwright' },
  { label: 'Qt', value: 'qt' },
  { label: 'React.js', value: 'reactjs' },
  { label: 'SaaS', value: 'saas' },
  { label: 'Scrapy', value: 'scrapy' },
  { label: 'Selenium', value: 'selenium' },
  { label: 'Svelte', value: 'svelte' },
  { label: 'Tensor F.', value: 'tensorflow' },
  { label: 'Terraform', value: 'terraform' },
  { label: 'TestCafe', value: 'testcafe' },
  { label: 'Vue.js', value: 'vuejs' },
  { label: 'Xamarin', value: 'xamarin' },
  { label: 'Wordpress', value: 'wordpress' },
];
