type IframeworkColors = Record<string, string>;

type IframeworkTextColors = Record<string, string>;

export const frameworkColors: IframeworkColors = Object.freeze({
  'ASP.NET': '#225FE5',
  Angular: '#BF2626',
  Backbone: '#225FE5',
  Bootstrap: '#6836D9',
  Django: '#08A642',
  Ember: '#BF2626',
  Express: '#FAFAFA',
  Figma: '#6836D9',
  Flask: '#0AA6BF',
  Flutter: '#0AA6BF',
  GraphQL: '#CC1FC3',
  Hadoop: '#0AA6BF',
  Illustrator: '#D9790B',
  KMM: '#CC1FC3',
  Laravel: '#BF2626',
  MUI: '#225FE5',
  NodeJS: '#73B212',
  NumPy: '#225FE5',
  Photoshop: '#225FE5',
  PyTorch: '#D9790B',
  React: '#0AA6BF',
  'React N.': '#0AA6BF',
  Redux: '#6836D9',
  Ruby: '#BF2626',
  Spark: '#D9790B',
  Spring: '#73B212',
  'Tensor F.': '#D9790B',
  VueJS: '#08A642',
  jQuery: '#225FE5',
});

export const frameworkTextColors: IframeworkTextColors = Object.freeze({
  'ASP.NET': 'white',
  Angular: 'white',
  Backbone: 'white',
  Bootstrap: 'white',
  Django: 'white',
  Ember: 'white',
  Express: '#1E1E1E',
  Figma: 'white',
  Flask: 'white',
  Flutter: 'white',
  GraphQL: 'white',
  Hadoop: 'white',
  Illustrator: 'white',
  KMM: 'white',
  Laravel: 'white',
  MUI: 'white',
  NodeJS: 'white',
  NumPy: 'white',
  Photoshop: 'white',
  PyTorch: 'white',
  React: 'white',
  'React N.': 'white',
  Redux: 'white',
  Ruby: 'white',
  Spark: 'white',
  Spring: 'white',
  'Tensor F.': 'white',
  VueJS: 'white',
  jQuery: 'white',
});
