export const frameworkOptions = [
  { label: 'NodeJS', value: 'nodejs' },
  { label: 'Ruby', value: 'ruby' },
  { label: 'Angular', value: 'angular' },
  { label: 'Hadoop', value: 'hadoop' },
  { label: 'Ember', value: 'ember' },
  { label: 'Django', value: 'django' },
  { label: 'Redux', value: 'redux' },
  { label: 'React', value: 'react' },
  { label: 'Spring', value: 'spring' },
  { label: 'Spark', value: 'spark' },
  { label: 'Backbone', value: 'backbone' },
  { label: 'Figma', value: 'figma' },
  { label: 'Photoshop', value: 'photoshop' },
  { label: 'jQuery', value: 'jquery' },
  { label: 'MUI', value: 'mui' },
  { label: 'ASP.NET', value: 'aspnet' },
  { label: 'NumPy', value: 'numpy' },
  { label: 'Flutter', value: 'flutter' },
  { label: 'React N.', value: 'reactnative' },
  { label: 'Flask', value: 'flask' },
  { label: 'VueJS', value: 'vuejs' },
  { label: 'Bootstrap', value: 'bootstrap' },
  { label: 'KMM', value: 'kotlinmultiplatformmobile' },
  { label: 'GraphQL', value: 'graphql' },
  { label: 'Laravel', value: 'laravel' },
  { label: 'PyTorch', value: 'pytorch' },
  { label: 'Tensor F.', value: 'tensorflow' },
  { label: 'Express', value: 'express' },
  { label: 'Illustrator', value: 'illustrator' },
];
