export const recommendedLanguages = {
  'Backend Developer': [
    { label: 'JavaScript', value: 'javascript' },
    { label: 'PHP', value: 'php' },
    { label: 'Python', value: 'python' },
    { label: 'Java', value: 'java' },
    { label: 'Go', value: 'go' },
  ],
  'Cyber Security': [
    { label: 'Java', value: 'java' },
    { label: 'C++', value: 'cpp' },
    { label: 'C', value: 'c' },
    { label: 'Assembly', value: 'assembly' },
    { label: 'Python', value: 'python' },
  ],
  'Data Engineer': [
    { label: 'Python', value: 'python' },
    { label: 'R', value: 'r' },
    { label: 'SQL', value: 'sql' },
    { label: 'Java', value: 'java' },
    { label: 'Scala', value: 'scala' },
  ],
  'Data Scientist': [
    { label: 'Python', value: 'python' },
    { label: 'R', value: 'r' },
    { label: 'SQL', value: 'sql' },
    { label: 'Java', value: 'java' },
    { label: 'Scala', value: 'scala' },
  ],
  'Database Developer': [
    { label: 'Python', value: 'python' },
    { label: 'R', value: 'r' },
    { label: 'SQL', value: 'sql' },
    { label: 'Java', value: 'java' },
    { label: 'Scala', value: 'scala' },
  ],
  'Desktop Applications Developer': [
    { label: 'Java', value: 'java' },
    { label: 'JavaScript', value: 'javascript' },
    { label: 'Kotlin', value: 'kotlin' },
    { label: 'Dart', value: 'dart' },
    { label: 'C#', value: 'csharp' },
  ],
  'DevOps Engineer': [
    { label: 'Python', value: 'python' },
    { label: 'Java', value: 'java' },
    { label: 'Go', value: 'go' },
    { label: 'PHP', value: 'php' },
    { label: 'JavaScript', value: 'javascript' },
  ],
  'Embedded Systems Developer': [
    { label: 'C', value: 'c' },
    { label: 'Rust', value: 'rust' },
    { label: 'Go', value: 'go' },
    { label: 'C++', value: 'cpp' },
    { label: 'Embedded C', value: 'embeddedc' },
  ],
  'Frontend/UI Developer': [
    { label: 'JavaScript', value: 'javascript' },
    { label: 'TypeScript', value: 'typescript' },
    { label: 'Python', value: 'python' },
    { label: 'Swift', value: 'swift' },
    { label: 'Java', value: 'java' },
  ],
  'Full-Stack Developer': [
    { label: 'JavaScript', value: 'javascript' },
    { label: 'Go', value: 'go' },
    { label: 'Python', value: 'python' },
    { label: 'PHP', value: 'php' },
    { label: 'Java', value: 'java' },
  ],
  'Machine Learning Engineer': [
    { label: 'Python', value: 'python' },
    { label: 'R', value: 'r' },
    { label: 'SQL', value: 'sql' },
    { label: 'Java', value: 'java' },
    { label: 'Scala', value: 'scala' },
  ],
  'Mobile Developer': [
    { label: 'Kotlin', value: 'kotlin' },
    { label: 'Swift', value: 'swift' },
    { label: 'Java', value: 'java' },
    { label: 'Javascript', value: 'javascript' },
    { label: 'TypeScript', value: 'typescript' },
  ],
  'No-code Developer': [
    // No specific programming languages recommended
  ],
  'QA/Test Engineer': [
    { label: 'Python', value: 'python' },
    { label: 'JavaScript', value: 'javascript' },
    { label: 'Java', value: 'java' },
    { label: 'Ruby', value: 'ruby' },
    { label: 'Go', value: 'go' },
    { label: 'Kotlin', value: 'kotlin' },
  ],
};
