export const recommendedDesignerTools = {
  '3D': [
    { value: 'cinema_4d', label: 'Cinema 4D' },
    { value: 'blender_3d', label: 'Blender 3D' },
    { value: 'spline', label: 'Spline' },
    { value: 'maya', label: 'Maya' },
    { value: '3ds_max', label: '3ds Max' },
    { value: 'zbrush', label: 'ZBrush' },
    { value: 'modo', label: 'Modo' },
    { value: 'houdini', label: 'Houdini' },
    { value: 'vectary', label: 'Vectary' },
    { value: 'substance_3d_designer', label: 'Substance 3D Designer' },
  ],
  Game: [
    { value: 'cinema_4d', label: 'Cinema 4D' },
    { value: 'blender_3d', label: 'Blender 3D' },
    { value: 'spline', label: 'Spline' },
    { value: 'maya', label: 'Maya' },
    { value: '3ds_max', label: '3ds Max' },
    { value: 'zbrush', label: 'ZBrush' },
    { value: 'modo', label: 'Modo' },
    { value: 'houdini', label: 'Houdini' },
    { value: 'vectary', label: 'Vectary' },
    { value: 'substance_3d_designer', label: 'Substance 3D Designer' },
  ],
  Graphic: [
    { value: 'photoshop', label: 'Photoshop' },
    { value: 'illustrator', label: 'Illustrator' },
    { value: 'indesign', label: 'InDesign' },
    { value: 'firefly', label: 'Firefly' },
    { value: 'midjourney', label: 'Midjourney' },
    { value: 'procreate', label: 'Procreate' },
  ],
  Illustration: [
    { value: 'photoshop', label: 'Photoshop' },
    { value: 'illustrator', label: 'Illustrator' },
    { value: 'procreate', label: 'Procreate' },
    { value: 'sketch', label: 'Sketch' },
    { value: 'firefly', label: 'Firefly' },
    { value: 'midjourney', label: 'Midjourney' },
  ],
  Motion: [
    { value: 'after_effects', label: 'After Effects' },
    { value: 'lottie', label: 'Lottie' },
    { value: 'premier_pro', label: 'Premier Pro' },
    { value: 'animate', label: 'Animate' },
    { value: 'illustrator', label: 'Illustrator' },
  ],
  Product: [
    { value: 'figma', label: 'Figma' },
    { value: 'xd', label: 'XD' },
    { value: 'sketch', label: 'Sketch' },
    { value: 'proto_pie', label: 'Proto Pie' },
    { value: 'invision', label: 'InVision' },
  ],
  SMM: [
    { value: 'canva', label: 'Canva' },
    { value: 'figma', label: 'Figma' },
    { value: 'photoshop', label: 'Photoshop' },
    { value: 'illustrator', label: 'Illustrator' },
    { value: 'sketch', label: 'Sketch' },
    { value: 'invision', label: 'InVision' },
  ],
  UI: [
    { value: 'figma', label: 'Figma' },
    { value: 'xd', label: 'XD' },
    { value: 'webflow', label: 'Webflow' },
    { value: 'readymag', label: 'Readymag' },
    { value: 'shopify', label: 'Shopify' },
    { value: 'framer', label: 'Framer' },
    { value: 'proto_pie', label: 'Proto Pie' },
    { value: 'invision', label: 'InVision' },
    { value: 'sketch', label: 'Sketch' },
  ],
  UX: [
    { value: 'figma', label: 'Figma' },
    { value: 'xd', label: 'XD' },
    { value: 'invision', label: 'InVision' },
    { value: 'sketch', label: 'Sketch' },
    { value: 'proto_pie', label: 'Proto Pie' },
  ],
  Web: [
    { value: 'webflow', label: 'Webflow' },
    { value: 'readymag', label: 'Readymag' },
    { value: 'framer', label: 'Framer' },
    { value: 'shopify', label: 'Shopify' },
    { value: 'weblium', label: 'Weblium' },
    { value: 'figma', label: 'Figma' },
    { value: 'xd', label: 'XD' },
  ],
};
